### ISSUE TITLE
给个建议。

### ISSUE THREAD

**Issue by cxj98** [torusrxxx/ExtraInfo#2]
那个插件已经实现了显示所有的 call，但是在 OD中，这些 call 可以单独显示要设置断点在哪一个 call 上，还有那个 infobox 能否设置成固定 4-5 行这样子就不能再调整了，那个边线都拉到天上去了。

你这个最好可以实现按 x 键的功能，就是鼠标右键在 infobox 的所有 call 上右键就能弹出按下 x键功能的 显示 所有 call 显示出来以后再选择要设置断点在哪一个 call 上。

**Comment by torusrxxx** [comment]
那个信息栏不能设置固定高度，而且也不支持设置点击事件，用户点击信息栏没用。目前这个插件可能是唯一一个会添加信息的插件，但不排除未来有人再编写其他的同类插件。

**Comment by cxj98** [comment]
![x32dbg infobox snapshot](https://cloud.githubusercontent.com/assets/11990617/20298665/13542e98-ab52-11e6-9acb-abf53357af8c.jpg)

**Comment by torusrxxx** [comment]
信息栏高度原来是锁定在3行高度不能调节的，后来我在官方版里添加了能让插件添加信息栏信息的接口，所以解锁了高度限制。信息栏没垂直滚动条，也不太好确定当安装了多个类似插件时高度限制是多少，不过，你可以选择不拉那么高啊。信息栏的高度是不保存的，每次重启软件，信息栏高度都会恢复默认3行高度。
