### ISSUE TITLE
1.01 的关闭了 x32dbg 会弹出两次错误

### ISSUE THREAD

**Issue by cxj98** [torusrxxx/ExtraInfo#3]
这个版本还是有点问题，关闭 x32dbg 会弹出两次崩溃的窗口。

**Comment by torusrxxx** [comment]
我这里没什么问题，可以说说是什么错误吗，升级x32dbg以后还有吗？

**Comment by cxj98** [comment]
问题签名:
  问题事件名称:   BEX
  应用程序名:  x32dbg.exe
  应用程序版本:   0.0.2.5
  应用程序时间戳:    582967b1
  故障模块名称:   StackHash_881a
  故障模块版本:   0.0.0.0
  故障模块时间戳:    00000000
  异常偏移: 07020fef
  异常代码: c0000005
  异常数据: 00000008
  OS 版本:    6.1.7601.2.1.0.256.1
  区域设置 ID:  2052
  其他信息 1:   881a
  其他信息 2:   881a15ceca462f1dcef287c3584dc560
  其他信息 3:   8fbf
  其他信息 4:   8fbf4858b60b2cf13fd00a279a42ca67

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment]
问题签名:
  问题事件名称:   APPCRASH
  应用程序名:  x32dbg.exe
  应用程序版本:   0.0.2.5
  应用程序时间戳:    582967b1
  故障模块名称:   StackHash_53c1
  故障模块版本:   0.0.0.0
  故障模块时间戳:    00000000
  异常代码: c000041d
  异常偏移: 07020fef
  OS 版本:    6.1.7601.2.1.0.256.1
  区域设置 ID:  2052
  其他信息 1:   53c1
  其他信息 2:   53c174a42c4a07592884a1bb525b0e87
  其他信息 3:   a101
  其他信息 4:   a101ee5ed6ddc602eda9c33c409a562b

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment]
第一个版本则无此问题，移除此插件，x32dbg 使用正常。

**Comment by torusrxxx** [comment]
现在应该好了吧。

**Comment by cxj98** [comment]
问题依旧，关闭 x32dbg 会弹出两次错误。

问题签名:
  问题事件名称:   BEX
  应用程序名:  x32dbg.exe
  应用程序版本:   0.0.2.5
  应用程序时间戳:    582967b1
  故障模块名称:   StackHash_881a
  故障模块版本:   0.0.0.0
  故障模块时间戳:    00000000
  异常偏移: 072c0fef
  异常代码: c0000005
  异常数据: 00000008
  OS 版本:    6.1.7601.2.1.0.256.1
  区域设置 ID:  2052
  其他信息 1:   881a
  其他信息 2:   881a15ceca462f1dcef287c3584dc560
  其他信息 3:   8fbf
  其他信息 4:   8fbf4858b60b2cf13fd00a279a42ca67

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment]
问题依旧，关闭 x32dbg 会弹出两次错误。

问题签名:
  问题事件名称:	BEX
  应用程序名:	x32dbg.exe
  应用程序版本:	0.0.2.5
  应用程序时间戳:	582967b1
  故障模块名称:	StackHash_881a
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常偏移:	072c0fef
  异常代码:	c0000005
  异常数据:	00000008
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	881a
  其他信息 2:	881a15ceca462f1dcef287c3584dc560
  其他信息 3:	8fbf
  其他信息 4:	8fbf4858b60b2cf13fd00a279a42ca67

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment]
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	x32dbg.exe
  应用程序版本:	0.0.2.5
  应用程序时间戳:	582967b1
  故障模块名称:	StackHash_53c1
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常代码:	c000041d
  异常偏移:	072c0fef
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	53c1
  其他信息 2:	53c174a42c4a07592884a1bb525b0e87
  其他信息 3:	a101
  其他信息 4:	a101ee5ed6ddc602eda9c33c409a562b

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment]
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	x32dbg.exe
  应用程序版本:	0.0.2.5
  应用程序时间戳:	582967b1
  故障模块名称:	StackHash_53c1
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常代码:	c000041d
  异常偏移:	072c0fef
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	53c1
  其他信息 2:	53c174a42c4a07592884a1bb525b0e87
  其他信息 3:	a101
  其他信息 4:	a101ee5ed6ddc602eda9c33c409a562b

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cxj98** [comment]
问题签名:
  问题事件名称:   APPCRASH
  应用程序名:  x32dbg.exe
  应用程序版本:   0.0.2.5
  应用程序时间戳:    582967b1
  故障模块名称:   StackHash_53c1
  故障模块版本:   0.0.0.0
  故障模块时间戳:    00000000
  异常代码: c000041d
  异常偏移: 072c0fef
  OS 版本:    6.1.7601.2.1.0.256.1
  区域设置 ID:  2052
  其他信息 1:   53c1
  其他信息 2:   53c174a42c4a07592884a1bb525b0e87
  其他信息 3:   a101
  其他信息 4:   a101ee5ed6ddc602eda9c33c409a562b

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by torusrxxx** [comment]
我把它安装到了最新版上，无论是在真机上还是Windows XP虚拟机上都没有报错，不知道你那是什么情况。

**Comment by torusrxxx** [comment]
已针对此问题做出一定修改。

**Comment by cxj98** [comment]
可惜新版本还没有提供下载。

**Comment by torusrxxx** [comment]
已经发到release里面了 1.03

**Comment by torusrxxx** [comment]
kao

**Comment by cxj98** [comment]
不是编译好的，那个只是源码，请提供编译好的插件成品下载。

**Comment by torusrxxx** [comment]
刷新了
