### ISSUE TITLE
请给解决看为什么这个插件跟其它的插件一起使用老是会有崩溃现象？

### ISSUE THREAD

**Issue by cxj98** [torusrxxx/ExtraInfo#5]
如果只用这个插件而不用其它的插件是没有任何问题的，但是如果跟其它的插件一起使用就会产生崩溃现像，就是关闭 x32dbg 以后会弹出两次崩溃调试器的错误提示，什么结果都没有保存，下次打开不是上次的结果，比如设置好了窗体，下次打开就无法记忆窗体大小和位置。

下载这个最新编译，最新插件集合包给测试一下。

链接：https://share.weiyun.com/784fcffe565541e81cd8abdbb3d35ba0 （密码：mdKjLf）

**Comment by torusrxxx** [comment]
我已经下载了，但是我没有安装python，所以我把和python有关的都删掉了。目前我仍在研究这个问题，看看是插件有问题，还是其他插件或者x64dbg本身有问题。

**Comment by torusrxxx** [comment]
我发现只要把文件名改为xxxxxxx.dp32，就没有错误信息了，但是不修改就有。

**Comment by torusrxxx** [comment]
这个错误与x64dbg本身或者其他插件有关，与本插件无关。解决方法如下This error is related to x64dbg itself or other plugins. This plugin is not responsible for the error. The solution is
1.  把文件名改个名字，比如“xxxxxxx.dp32”，就没有错误了。Rename this file to "xxxxxxx.dp32"
2.  退出之前用pluginunload命令首先将这个插件卸载，也没有错误。Use "pluginunload" command to unload this plugin first.
